###################################################################
# Twister2 Job Master related settings
###################################################################

# if true, the job master runs in the submitting client
# if false, job master runs as a separate process in the cluster
# by default, it is true
# when the job master runs in the submitting client, this client has to be submitting the job from a machine in the cluster
twister2.job.master.runs.in.client: false

# twister2 job master port number
# default value is 11111
twister2.job.master.port: 11011
#twister2.job.master.port: 2023

# worker to job master response wait time in milliseconds
# this is for messages that wait for a response from the job master
# default value is 10seconds = 10000
twister2.worker.to.job.master.response.wait.duration: 10000

# twister2 job master volatile volume size in GB
# default value is 1.0 Gi
# if this value is 0, volatile volume is not setup for job master
twister2.job.master.volatile.volume.size: 1.0

# twister2 job master persistent volume size in GB
# default value is 1.0 Gi
# if this value is 0, persistent volume is not setup for job master
twister2.job.master.persistent.volume.size: 1.0

# twister2 job master cpu request
# default value is 0.2 percentage
twister2.job.master.cpu: 0.2

# twister2 job master RAM request in MB
# default value is 0.2 percentage
twister2.job.master.ram: 1000

twister2.job.master.ip: "149.165.150.81"

###################################################################################
# WorkerController related config parameters
###################################################################################

# amount of timeout for all workers to join the job
# in milli seconds
twister2.worker.controller.max.wait.time.for.all.workers.to.join: 100000

# amount of timeout on barriers for all workers to arrive
# in milli seconds
twister2.worker.controller.max.wait.time.on.barrier: 100000

###################################################################
# Dashboard related settings
###################################################################

# Dashboard server host address and port
# if this parameter is not specified, then job master will not try to connect to Dashboard
# twister2.dashboard.host: "http://localhost:8080"
