################################################################################
# Client configuration parameters for submission of twister2 jobs
################################################################################

# twister2 job name
twister2.job.name: "basic-kubernetes"

# number of cores for each worker
# it is a floating point number
# each worker can have fractional cores such as 0.5 cores or multiple cores as 2
# default value is 1.0 core
twister2.worker.cpu: 1.0

# amount of memory for each worker in the job in mega bytes as integer
# default value is 200 MB
twister2.worker.ram: 200

# amount of hard disk space on each worker in mega bytes
# this only used when running twister2 in Aurora
# default value is 1024 MB. 
twister2.worker.disk: 1024

# number of worker instances
twister2.worker.instances: 6

########################################################################
# Kubernetes related settings
########################################################################
# namespace to use in kubernetes
# default value is "default"
# kubernetes.namespace: "default"

# number of workers (containers) per pod
# default is 1
# twister2.worker.instances must be divisible by containers_per_pod
kubernetes.workers.per.pod: 2

########################################################################
# persistent volume related settings
########################################################################
# Do workers request persistent volume? it could be true or false
# default value is false
persistent.volume.requested: true

# Do workers request persistent logging? it could be true or false
# default value is false
persistent.logging.requested: true

# it could be "system" or "kubernetes"
# system logging puts less load on the kubernetes master but it may not show some logs from startup
# kubernetes logging gets the log messages from kubernetes master but it is more complete
persistent.logging.type: "system"

# nfs server address
nfs.server.address: "149.165.150.81"

# nfs server path
nfs.server.path: "/nfs/shared"

# worker persistent volume size
# volume size suffixes: Mi, Gi
persistent.volume.per.worker: "1Gi"

# total persistent volume size for all workers in this job
# must be equal or higher than the total of all worker persistent volume sizes
# volume size suffixes: Mi, Gi
persistent.volume.total: "100Gi"

# the admin should provide a PersistentVolume object with the following storage class. 
# Default storage class name is "twister2".
kubernetes.persistent.storage.class: "twister2"

# persistent storage access mode. 
# It shows the access mode for workers to access the shared persistent storage.
# if it is "ReadWriteMany", many workers can read and write
# other alternatives: "ReadWriteOnce", "ReadOnlyMany"
# https://kubernetes.io/docs/concepts/storage/persistent-volumes
kubernetes.storage.access.mode: "ReadWriteMany"

# what happens to the storage after the job has finished
# the storage can be retained (Retain), or deleted (Delete)
# default value is "Retain"
kubernetes.storage.reclaim.policy: "Retain"

