# twister2.network.channel.class: "edu.iu.dsc.tws.comms.dfw.DataFlowCommunication"
twister2.network.channel.class: "edu.iu.dsc.tws.comms.dfw.tcp.TWSTCPChannel"

#############################################################################
# OpenMPI settings
#############################################################################
# By default, OpenMPI is not enabled
# To use OpenMPI, set this to true
kubernetes.workers.use.openmpi: false

# A Secret object must be present in Kubernetes master
# Its name must be specified here
kubernetes.secret.name: "twister2-openmpi-ssh-key"


#############################################################################
# Worker port settings
#############################################################################
# the base port number workers will use internally to communicate with each other
# when there are multiple workers in a pod, first worker will get this port number, 
# second worker will get the next port, and so on.
# default value is 9999, 
# kubernetes.worker.base.port: 9999

# transport protocol for the worker. TCP or UDP
# by default, it is TCP
# set if it is UDP
# kubernetes.worker.transport.protocol: "TCP"

#############################################################################
# NodePort service parameters
#############################################################################

# if the job requests NodePort service, it must be true
# NodePort service makes the workers accessibale from external entities (outside of the cluster)
# by default, its value is false
# kubernetes.node.port.service.requested: true

# if NodePort value is 0, it is automatically assigned a value
# the user can request a specific port value in the NodePort range by setting the value below
# by default Kubernetes uses the range: 30000-32767 for NodePorts
# Kubernetes admins can change this range
# kubernetes.service.node.port: 30003

