#############################################################################
# OpenMPI settings
#############################################################################
# If the channel is set as TWSMPIChannel,
# the job is started as OpenMPI job
# Otherwise, it is a regular twister2 job. OpenMPI is not started in this case.

# twister2.network.channel.class: "edu.iu.dsc.tws.comms.dfw.mpi.TWSMPIChannel"
twister2.network.channel.class: "edu.iu.dsc.tws.comms.dfw.tcp.TWSTCPChannel"

# A Secret object must be present in Kubernetes master
# Its name must be specified here
kubernetes.secret.name: "twister2-openmpi-ssh-key"

#############################################################################
# Worker port settings
#############################################################################

# the base port number workers will use internally to communicate with each other
# when there are multiple workers in a pod, first worker will get this port number,
# second worker will get the next port, and so on.
# default value is 9000,
# kubernetes.worker.base.port: 9000

# transport protocol for the worker. TCP or UDP
# by default, it is TCP
# set if it is UDP
# kubernetes.worker.transport.protocol: "TCP"

#############################################################################
# NodePort service parameters
#############################################################################

# if the job requests NodePort service, it must be true
# NodePort service makes the workers accessibale from external entities (outside of the cluster)
# by default, its value is false
# kubernetes.node.port.service.requested: true

# if NodePort value is 0, it is automatically assigned a value
# the user can request a specific port value in the NodePort range by setting the value below
# by default Kubernetes uses the range: 30000-32767 for NodePorts
# Kubernetes admins can change this range
# kubernetes.service.node.port: 30003

# the buffer size to be used
network.buffer.size: 1024000

# number of send buffers to be used
network.sendBuffer.count: 4

# number of receive buffers to be used
network.receiveBuffer.count: 4

# channel pending messages
network.channel.pending.size: 2048

# the send pending messages
network.send.pending.max: 4

# group up to 8 ~ 16 messages
network.partition.message.group.low_water_mark: 8

# this is the max number of messages to group
network.partition.message.group.high_water_mark: 16

# the maximum amount of bytes kept in memory for operations that goes to disk
shuffle.memory.bytes.max: 1024000

# the maximum number of records kept in memory for operations that goes to dist
shuffle.memory.records.max: 10240

# the keyed reduce algorithm
twister2.keyed.reduce.op: "partition"

# the algorithm for gathering data
twister2.keyed.gather.op: "partition"

# the partitioning algorithm
twister2.partition.algorithm: "simple"
