# the package uri
twister2.system.package.uri: "${TWISTER2_DIST}/twister2-core.tar.gz"
# the resource manager class
twister2.class.state.manager: "edu.iu.dsc.tws.rsched.statemanagers.fs.SharedFileSystemStateManager"
# launcher class for aurora submission
twister2.class.launcher: edu.iu.dsc.tws.rsched.schedulers.aurora.AuroraLauncher
# the uplaoder class
twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.scp.ScpUploader"
# twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.NullUploader"
# twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"

# container class to run in workers
twister2.job.basic.container.class: "edu.iu.dsc.tws.examples.basic.BasicAuroraContainer"

# the Aurora worker class
twister2.class.aurora.worker: "edu.iu.dsc.tws.rsched.schedulers.aurora.AuroraWorker"

###################################################################################
# ZooKeeper related config parameters
###################################################################################
# ZooKeeper server ip address and port number
twister2.zookeeper.server.ip: "149.165.150.81"
twister2.zookeeper.server.port: "2181"

# the root node path of this job on ZooKeeper
# the default is "/twister2"
#twister2.zookeeper.root.node.path: "/twister2"

# if the workers want to wait for all others to join a job, max wait time in ms
twister2.zookeeper.max.wait.time.for.all.workers.to.join: "100000"


