twister2.network.channel.class: "edu.iu.dsc.tws.comms.dfw.mpi.TWSMPIChannel"

network.mpi.buffer.size: 1024000
network.mpi.sendBuffer.count: 4
network.mpi.receiveBuffer.count: 4
# channel pending messages
network.channel.mpi.pending.size: 2048
# the send pending messages
network.mpi.send.pending.max: 4

# group up to 8 ~ 16 messages
network.partition.message.group.low_water_mark: 8
network.partition.message.group.high_water_mark: 16