#Home directory of the hadoop
twister2.hadoop.home: "${HADOOP_HOME}"

#Specify the URL of the namenode with port
twister2.hdfs.url: "hdfs://namenode:9000"

#specify the hdfs class
twister2.hdfs.class: "org.apache.hadoop.hdfs.DistributedFileSystem"

#Specify the hdfs key
twister2.hdfs.implementation.key: "fs.hdfs.impl"

#Specify the config directory of the hdfs
twister2.hdfs.config.directory: "${HADOOP_HOME}/etc/hadoop/core-site.xml"

#Specify the data directory of the hdfs
twister2.hdfs.data.directory: "/user/username/"

#Specify the name of the namenode
twister2.hdfs.namenode: "namenode.iu.edu"

#Specify the namenode port
twister2.hdfs.namenode.port: "9000"
