###################################################################
# Twister2 Job Master related settings
###################################################################

twister2.job.master.used: true

# if true, the job master runs in the submitting client
# if false, job master runs as a separate process in the cluster
# by default, it is true
# when the job master runs in the submitting client, this client has to be submitting the job from a machine in the cluster
twister2.job.master.runs.in.client: true

# if true, job master assigns the worker IDs,
# if false, workers have their IDs when regitering with the job master
twister2.job.master.assigns.worker.ids: false

twister2.worker.to.job.master.response.wait.duration: 100000

###################################################################################
# WorkerController related config parameters
###################################################################################

# amount of timeout for all workers to join the job
# in milli seconds
twister2.worker.controller.max.wait.time.for.all.workers.to.join: 100000

# amount of timeout on barriers for all workers to arrive
# in milli seconds
twister2.worker.controller.max.wait.time.on.barrier: 100000

###################################################################
# Dashboard related settings
###################################################################

# Dashboard server host address and port
# if this parameter is not specified, then job master will not try to connect to Dashboard
# twister2.dashboard.host: "http://localhost:8080"
