#Home directory of the hadoop
twister2.data.hadoop.home: "${HADOOP_HOME}"

#Specify the config directory of the hdfs
twister2.data.hdfs.config.directory: "${HADOOP_HOME}/etc/hadoop/core-site.xml"

#Specify the data directory of the hdfs
twister2.data.hdfs.data.directory: "${HADOOP_HOME}/etc/hadoop/hdfs-site.xml"

#Specify the name of the namenode
twister2.data.hdfs.namenode: "localhost"

#Specify the namenode port
twister2.data.hdfs.namenode.port: "9001"

# twister2.data.fs.root: "${TWISTER2_HOME}/persistent/data"
twister2.data.fs.root: "${TWISTER2_HOME}/persistent"

twister2.data.hdfs.root: "/twister2/persistent/data"
