# use this property to debug the client submitting the job
# twister2.client.debug: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5006'

# Weather we have a requirement to copy the system package
twister2.resource.systempackage.copy: false

###################################################################################
# ZooKeeper related config parameters
###################################################################################

# ZooKeeper can be used to exchange job status data and discovery
# Workers can discover one another through ZooKeeper
# They update their status on ZooKeeper
# Dashboard can get job events through ZooKeeper
# If fault tolerance is enabled, ZooKeeper is used, irrespective of this parameter
twister2.zookeeper.based.group.management: true

# ZooKeeper server addresses: comma separated host:port pairs
# example: "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002"
# when conf/kubernetes/deployment/zookeeper-wo-persistence.yaml is used
# following service name can be used as zk address
twister2.resource.zookeeper.server.addresses: "twister2-zookeeper.default.svc.cluster.local:2181"
#twister2.resource.zookeeper.server.addresses: "ip:port"

# the root node path of this job on ZooKeeper
# the default is "/twister2"
# twister2.zookeeper.root.node.path: "/twister2"
